/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.user.api;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.ComponentScan;

@SpringBootApplication
public class Application {

    public static void main(String[] args) {
	    SpringApplication.run(Application.class, args);
    }
}
