version: '3.8'
services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: user-db
      MYSQL_USER: cpardo
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: admin
    ports:
      - 3306:3306
    volumes:
      - ./insert.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - user_private
    container_name: user-api-mysql-container

  adminer:
    image: adminer
    restart: always
    ports:
      - 8000:8080
    container_name: user-api-adminer-container
    depends_on:
      - mysql
    networks:
      - user_private

  spring-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - mysql
    networks:
      - user_private
    environment:
      MYSQL_USER: cpardo
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: admin
    container_name: user-api-be-spring-container

networks:
  user_private:
    driver: bridge