version: '3.8'
services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: mygamemmo
      MYSQL_USER: cpardo
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: admin
    ports:
      - 3306:3306
    volumes:
      - ./insert.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - private_private
    container_name: mygamemmo-mysql-container

  spring-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - mysql
    networks:
      - private_private
    environment:
      MYSQL_USER: cpardo
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: admin
    container_name: mygamemmo-be-spring-container

networks:
  private_private:
    driver: bridge