spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mygamemmo
    username: cpardo
    password: admin
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
    show-sql: true