spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:mysql://localhost:3306/user-db
    username: cpardo
    password: admin
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
    show-sql: true

jwt:
  secret: BtkZvurU6Jh6iO/IxXq75v31EMsWjdnO6BwU7s3R1oM=
  expiration: 300000